Update `key_colnames`, `revision_summary`
cmu-delphi/epiprocess pull request #540
Opened 2024-10-10 17:01 UTC by brookslogan

### Checklist

Please:

- [ ] Make sure this PR is against "dev", not "main" (unless this is a release
      PR).
- [ ] Request a review from one of the current main reviewers:
      brookslogan, nmdefries.
- [ ] Makes sure to bump the version number in `DESCRIPTION`. Always increment
      the patch version number (the third number), unless you are making a
      release PR from dev to main, in which case increment the minor version
      number (the second number).
- [ ] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      1.7.2, then write your changes under the 1.8 heading).
- See [DEVELOPMENT.md](DEVELOPMENT.md) for more information on the development
  process.

### Change explanations for reviewer

- Make `key_colnames.epi_archive` output its unique key colnames (including version).
- Make `key_colnames.data.frame` require `other_keys` to be passed.
- Remove `key_colnames.default`.
- Require `exclude =` to be passed by name in `key_colnames`.
- Require dots to be empty in `key_colnames`.
  - Note: this triggers some errors in epipredict tests.  See below.
- Update `revision_summary` to use new `key_colnames.epi_archive`.
- Fix&tweak some tidyeval stuff in `revision_summary`.
- Tweak some naming in `revision_summary`.

#### `epipredict` errors

Originally, I misread and thought these were from passing `other_keys =` hopefully-redundantly into `key_colnames.epi_df` and having them be ignored.  I was planning to do something like
```r
  expected_other_keys <- attr(x, "metadata")$other_keys
  if (is.null(other_keys)) {
    other_keys <- expected_other_keys
  } else {
    if (!identical(other_keys, expected_other_keys)) {
      cli_abort(c(
        "`other_keys` was provided, but didn't match expectations from inspecting `x`",
        "*" = "`other_keys` was {format_chr_with_quotes(other_keys)}",
        "*" = "`expected_other_keys` was {format_chr_with_quotes(expected_other_keys)}",
        "i" = "If you resolve this discrepancy by adjusting the metadata of `x`, you
               shouldn't have to pass `other_keys =` here anymore unless you want to
               continue to perform this check."
      ))
    }
  }
```
However, the error is actually from passing `extra_keys =` (which was previously ignored).  I am looking a bit more into this.

- [ ] todo: decide what to do re. `extra_keys =`
- [ ] todo: check whether epipredict#410 is caught... requiring `other_keys =` in `key_colnames.data.frame` should be flagging this, right?

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #{issue number}

2025-01-10 19:45 UTC, brookslogan commented
@dsweber2 do you have time to take a look over these changes?  I was really just wanting to update to use the `key_colnames` changes from the dependent PR, but a couple "quick adjustments" and CHECK and lint yelling and it may be partway to #557.

2025-01-10 21:10 UTC, dsweber2 commented
yes, I'm no longer in 100% forecast pipeline mode. I'll put this as high priority

2025-01-10 23:31 UTC, dsweber2 requested changes
I added a commit with some minor logic refactors and comments for things I found unclear (some of which came from stuff I wrote long enough ago). `lag` is definitely a better name for a bunch of these columns than `time`.

I think committing to using `week`s or `month`s for `version` comes with some assumptions about versioning behavior that we may not want to be making. What happens with weekly data released at a daily cadence, for example?

I do think we could probably put these utilities to use elsewhere, but I'm not sure this is the PR for them.

2025-01-10 23:31 UTC, dsweber2 commented on tests/testthat/test-revision-latency-functions.R
> +  expect_equal(
wasn't able to annotate this one, not quite sure what the difference is supposed to be.

2025-01-10 23:31 UTC, dsweber2 commented on tests/testthat/test-revision-latency-functions.R
> +  expect_equal(
I guess this is weekly data?

2025-01-13 18:37 UTC, brookslogan commented on R/archive.R
> +  lag_vec <- vec_position_lag(vec, 1L)
Oops.  This was to fix compactification on `dist_quantiles` columns.  Might be missing an issue number somewhere.
- [ ] update function docs
- [ ] check for / add test

2025-01-13 18:42 UTC, brookslogan commented on R/revision_analysis.R
> +      filter(time_value <= last_semistable_time_value)
The is to make it work with additional `time_type`s while attempting to limit the number of time helpers introduced.  (Though looking into the future, if we want this function to work on weekly-time daily-version or weekly-time datetime-version, then we may need to add the helpers I was hoping to avoid to calculate a `waiting_period` and compare to `min_waiting_period` as before...) 

(The delta for this particular line also cleans up an `abs()` call that didn't seem to belong.)

2025-01-13 18:45 UTC, brookslogan commented on tests/testthat/test-revision-latency-functions.R
> +  expect_equal(
- [ ] add comments re. time_type

2025-01-13 18:51 UTC, brookslogan commented on R/time-utils.R
"Most" of this `time_type` stuff was already in a separate (though not dedicated; it mixed in the `epi_slide_opt` naming changes) PR.  The stuff added here is specific to
1. Making `revision_summary()` work when it sets defaults in terms of days that may not be integerish when converted to the relevant `time_type`.
2. Making defaults [non-magical](https://design.tidyverse.org/def-magical.html) while still attempting to make them "readable", or some other difficulty there I don't quite recall.

Does this change your perspective?  What other utilities should they be applied to first?

2025-01-13 19:05 UTC, brookslogan commented on R/revision_analysis.R
> +      filter(time_value <= last_semistable_time_value)
The hypothetical time helper I mentioned above (which would calculate `version - time_value` more generically and factoring in time type(s) involved)  seems to require some thought to implement, probably not something we want to do now.

Details:
This helper probably also needs starting/ending-wday metadata that you have described to output the expected result for the intermediate variable `waiting_period`.  The Hubverse/we conventionally seem to call Sunday lag 1 relative to a Sun--Sat week regardless of what the representation wday is.  Though for the purpose of `revision_summary()`, we'd probably need to sort of reverse that special handling so that `min_waiting_period` means the same thing regardless of the representation weekday.  Messy.   Or maybe it's actually that Hubverse is using the ending wday as the representation wday?  Perhaps that could make this simpler.

2025-01-13 19:10 UTC, brookslogan commented on R/revision_analysis.R
> +    mutate(lag = time_minus_time_in_n_steps(version, time_value, time_type)) %>% # nolint: object_usage_linter
I couldn't figure out a way to keep lags in days for yearmonth or integer + wanted to try to make the arguments more in line with `.window_size` and `.before` for slides.  But at the same time, the defaults in days seemed the way to go... leading to some of the additions in the time utilities.

2025-01-13 19:15 UTC, brookslogan commented
> I think committing to using weeks or months for version comes with some assumptions about versioning behavior that we may not want to be making. What happens with weekly data released at a daily cadence, for example?

Definitely.  But that's what we've already assumed in the archive construction.  I was hoping to just make multiple time types work given our current assumptions and handle relaxing this assumption later.  Maybe there are two options here:
- Try to excise some of the time type stuff from this PR, relax the assumptions first, then re-introduce time type stuff to this function after we've done that.
- Work with this PR as-is, and as we relax the assumptions later, revisit the design of some of the time helpers / their usage here.

Preferences / other options?

2025-01-13 23:32 UTC, brookslogan commented on R/archive.R
> +  lag_vec <- vec_position_lag(vec, 1L)
- [ ] remove `n` or fix partial implementation

2025-01-13 23:54 UTC, brookslogan commented on R/archive.R
> +  lag_vec <- vec_position_lag(vec, 1L)
- [ ] track down what the failing example actually was.  Maybe it wasn't `dist_quantiles` but something else in a forecast archive.  dplyr 1.1.0 seems like it fixes dplyr::lag on dist_quantiles.

2025-01-14 01:32 UTC, brookslogan commented on R/archive.R
> +  lag_vec <- vec_position_lag(vec, 1L)
Okay, I ended up just nixing `vec_position_lag` as it appears unnecessary now that we require dplyr >= 1.1.0.  There's probably some performance we could squeeze out of a specialized implementation if we find compactification / revision analysis to be slow at some point.

I added a test for the thing that was broken + made it actually work.

One thing I came across: `vec_equal(x, y, na_equal = TRUE)` --- takes care of all the NA-comparison stuff we were doing manually before, seems pretty nice.

2025-01-15 18:35 UTC, brookslogan commented on R/time-utils.R
> +difftime_approx_ceiling_time_delta <- function(difftime, time_type) {
Added!

2025-01-16 00:04 UTC, brookslogan commented on R/revision_analysis.R
> +    mutate(lag = time_minus_time_in_n_steps(version, time_value, time_type)) %>% # nolint: object_usage_linter
Added tests + addressed some bugs.

2025-01-16 17:35 UTC, dsweber2 approved these changes
looks good to me! A few docs suggestions you can take or leave

2025-01-16 17:35 UTC, dsweber2 commented on R/key_colnames.R
>  #' @param x an object, such as an [`epi_df`]
```suggestion
#' @param x a table, such as a [`'tibble`], [`epi_df`], or [`epi_archive`]
```

2025-01-16 17:35 UTC, dsweber2 commented on R/key_colnames.R
> +#'   definitely an `epi_df`.)
```suggestion
#'   `epi_df` or `epi_archive`; the defaults are `"geo_value"`, the `epi_df`'s `other_keys`
#'   metadata, and `"time_value"`, respectively; if you provide these manually,
#'   they must match the defaults. (This behavior is to enable consistent and
#'   sane results when you can't guarantee the type of `x`. You don't need to use it if
#'   you know that `x` is definitely an `epi_df` or `epi_archive`.)
```

2025-01-24 07:59 UTC, brookslogan commented on DESCRIPTION
> +    epipredict,
Hmm, we can probably refactor this out when epipredict gets split into its parts.  I think this should be fine until then, though:
- Suggests: shouldn't make it actually try to load epipredict before epiprocess.  The [R extensions manual](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html) seems clear about that.
- Seems to have worked out for r-lib & tidyverse with vctrs-pillar and pillar-dplyr.

(The more confusing circularish dependence is how epidatasets is structured, due to details regarding data sets, laziness, load order, ...)

2025-01-24 08:02 UTC, brookslogan commented on R/key_colnames.R
> +#'   if `x` is a regular `data.frame` or `tibble`. Optional if `x` is an
Nice!  I've been paranoid about paragraph breaks breaking stuff instead and moving it to random other locations since one / a couple incidents when that seemed to have occurred, but this doesn't seem to be one of those situations.

2025-01-24 08:10 UTC, brookslogan commented on R/key_colnames.R
>  #' @param x an object, such as an [`epi_df`]
I felt I had to change it the opposite direction because `epipredict` adds implementations for non-table-y things.  Side note: `"table"` is actually a base R class for (N-dimensional) contingency tables (counting appearances of possible combinations of values of N factor/integer variables).

2025-01-24 08:22 UTC, brookslogan commented on R/key_colnames.R
>  #' @param x an object, such as an [`epi_df`]
Just hedged a bit instead.

2025-01-24 08:28 UTC, brookslogan commented on R/key_colnames.R
> +#'   definitely an `epi_df`.)
Added text for `epi_archive` and `tsibble`s.  I didn't actually add support for these args for them in the associated implementations at all; I just tried to do something to try to help with making epipredict transition to more fully supporting `other_keys` and it doesn't use those at all.  Though other changes in epipredict may actually make these arguments and the `data.frame` implementation unnecessary altogether...  Keeping them here temporarily just to not trip epipredict dev up if it's found that this feature is needed.

2025-01-24 09:32 UTC, merged